### ISSUE TITLE
fatal error with go 1.13.4 on mac env 

### ISSUE THREAD

**Issue by asafambar** [gen2brain/go-unarr#10]
Hi, 
I'm using go 1.13.4.
When trying to open 7z file with `NewArchive` the app colapse with `runtime.sigpanic()`
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff72777476]

runtime stack:
runtime.throw(0x53f81e8, 0x2a)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/signal_unix.go:378 +0x47c

goroutine 72 [syscall]:
runtime.cgocall(0x4fe9770, 0xc000c85a28, 0xc000000000)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/cgocall.go:128 +0x5b fp=0xc000c859f8 sp=0xc000c859c0 pc=0x400520b
github.com/gen2brain/go-unarr._Cfunc_ar_open_7z_archive(0xa700630, 0x0)
	_cgo_gotypes.go:194 +0x4a fp=0xc000c85a28 sp=0xc000c859f8 pc=0x41673ba
github.com/gen2brain/go-unarr.(*Archive).open.func3(0xc000346650, 0x0)
	pkg/mod/github.com/gen2brain/go-unarr@v0.0.0-20190203132630-dd30f8db8e40/unarr.go:81 +0x5e fp=0xc000c85a68 sp=0xc000c85a28 pc=0x4168cde
github.com/gen2brain/go-unarr.(*Archive).open(0xc000346650, 0xa700630, 0xa7005d0)
	pkg/mod/github.com/gen2brain/go-unarr@v0.0.0-20190203132630-dd30f8db8e40/unarr.go:81 +0x107 fp=0xc000c85a90 sp=0xc000c85a68 pc=0x4167cb7
github.com/gen2brain/go-unarr.NewArchive(0xc0000b06c0, 0x55, 0xc000346650, 0x0, 0x0)
	pkg/mod/github.com/gen2brain/go-unarr@v0.0.0-20190203132630-dd30f8db8e40/unarr.go:41 +0xe0 fp=0xc000c85af8 sp=0xc000c85a90 pc=0x4167b10
```

I downgraded to go 1.12.12 and it works fine. 
This led me to the conclusion it doesn't work with go 1.13.

**Comment by asafambar** [comment]
UPDATE:
after upgrading to 1.13.8 things works fine.
